import { MainNav } from "@/components/Structure/main-nav";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <MainNav />
      <main className="bg-zinc-200 text-foreground  min-h-screen items-center justify-between ">
        {children}
      </main>
    </>
  );
}
